=== abes-esr/qualinka-sudoc/web-services/src/main/resources/json-schemas/cluster-input.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "cluster module input",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"scenario",
		"sources",
		"targets",
		"features"
	],
	"properties": {
		"scenario": {
			"type": "string"
		},
		"options": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"debug": {
					"type": "boolean"
				},
				"validatedSameAsThreshold": {
					"type": "integer"
				},
				"suggestedSameAsThreshold": {
					"type": "integer"
				},
				"validatedDiffFromThreshold": {
					"type": "integer"
				},
				"suggestedEnabled": {
					"type": "boolean"
				},
				"keepOnlyBestSuggestions": {
					"type": "boolean"
				},
				"exportCriterionValues": {
					"type": "boolean"
				},
				"dataValidationEnabled": {
					"type": "boolean"
				}
			}
		},
		"sources": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"targets": {
			"oneOf": [
				{
					"type": "array",
					"items": {
						"type": "string"
					},
					"minItems": 1,
					"uniqueItems": true
				},
				{
					"enum": [
						"sources"
					]
				}
			]
		},
		"supports": {
			"oneOf": [
				{
					"type": "array",
					"items": {
						"type": "string"
					},
					"minItems": 0,
					"uniqueItems": true
				},
				{
					"enum": [
						"sources"
					]
				}
			]
		},
		"safeLinks": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"type": {
						"type": "string"
					},
					"source": {
						"type": "string"
					},
					"target": {
						"type": "string"
					}
				},
				"required": [
					"type",
					"source",
					"target"
				],
				"additionalProperties": false
			}
		},
		"features": {
			"type": "object"
		},
		"initialLinks": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"type": {
						"enum": [
							"sameAs",
							"diffFrom"
						]
					},
					"source": {
						"type": "string"
					},
					"target": {
						"type": "string"
					}
				},
				"required": [
					"type",
					"source",
					"target"
				],
				"additionalProperties": false
			}
		}
	}
}

=== abes-esr/qualinka-sudoc/linking-scenarios-example/src/test/resources/many-to-one.json
{
	"scenario": "example-many-to-one",
	"options": { "debug": true },
	"sources": ["rc:1", "rc:2", "rc:3", "rc:4"],
	"targets": ["ra:1", "ra:2", "ra:3"],
	"supports": "sources",
	"features": {
		"rc:1": {
			"name": "Durant, Émilie",
			"publicationDate": 1921,
			"title": "Les fleurs du Moyen-Orient",
			"domain": [ 580 ]
		},
		"rc:2": {
			"name": "Durant, Émilie",
			"publicationDate": 1924,
			"title": "Les fleurs d'Europe"
		},
		"rc:3": {
			"name": "Durant, Émilie",
			"publicationDate": 1926,
			"title": "Les fleurs d'Asie",
			"domain": [ 580 ]
		},
		"rc:4": {
			"name": "Durant, Émilie",
			"publicationDate": 1928,
			"title": "Les fleurs d'Amérique"
		},
		"ra:1": {
			"name": "DURANT, EMILIE",
			"birthDate": 1963
		},
		"ra:2": {
			"name": "Durant, Émilie",
			"domain": [ 340 ]
		},
		"ra:3": {
			"name": "  dürànt, èmîlïè   ",
			"birthDate": 1900,
			"source": "les fleurs du moyen-orient"
		}
	}
}

=== abes-esr/qualinka-sudoc/linking-scenarios-sudoc/src/test/resources/RCRC/align.json
{
	"scenario": "sudoc-ra-ra",
	"sources": [
		"ra1",
		"ra2",
		"ra3",
		"ra4",
		"ra5",
		"ra6"
	],
	"targets": "sources",
	"features": {
		"ra1": {
			"source": ["le r√©seau secret de l'abes / abes blabla, 1994 "],
			"personName": ["dupont, jean-marie"],
			"birthDate": "19660707",
			"deathDate": "2004",
			"externalId": ["hal:3", "haribo:pik"]
		},
		"ra2": {
			"personName": ["dupont, jean-marie"],
			"externalId": ["orcid:1", "hal:3"]
		},
		"ra3": {
			"source": ["le reseau secret de l'ABES / abes blabla, 1994 "],
			"personName": ["dupont, jean-marie"]
		},
		"ra4": {
			"personName": ["dupont, jean-marie"],
			"birthDate": "1966",
			"deathDate": "2004"
		},
		"ra5": {
			"personName": ["dupont, jean-marie"],
			"birthDate": "19660707"
		},
		"ra6": {
			"personName": ["dupont, jean-marie"],
			"birthDate": "19660707",
			"deathDate": "2015"
		}
	}
}

=== abes-esr/qualinka-sudoc/linking-scenarios-example/src/test/resources/many-to-many.json
{
	"scenario": "example-many-to-many",
	"options": { "debug": false },
	"sources": ["rc:1", "rc:2", "rc:3", "rc:4", "rc:5", "rc:6"],
	"targets": "sources",
	"features": {
		"rc:1": {
			"name": "Durant, Émilie",
			"publicationDate": 1921,
			"title": "Les fleurs du Moyen-Orient",
			"domain": [ 580 ]
		},
		"rc:2": {
			"name": "Durant, Émilie",
			"publicationDate": 1924,
			"title": "Les fleurs d'Europe"
		},
		"rc:3": {
			"name": "Durant, Émilie",
			"publicationDate": 1926,
			"title": "Les fleurs d'Asie",
			"domain": [ 580 ]
		},
		"rc:4": {
			"name": "Durant, Émilie",
			"publicationDate": 1928,
			"title": "Les fleurs d'Amérique"
		},
		"rc:5": {
			"name": "Durant, Émilie",
			"publicationDate": 1858,
			"title": "Les graphes conceptuels, un représentation graphique des connaissances"
		},
		"rc:6": {
			"name": "Durant, Émilie",
			"publicationDate": 1865,
			"title": "Graphes et représentation des connaissances"
		}
	}
}
